#+TITLE: Information Theory: Problem Set 1
#+AUTHOR: Marcos Vinicius Moreira Santos 
#+OPTIONS: toc:nil        (no default TOC at all)
#+BEGIN_abstract
This document contains my answers for the questions at  https://homepages.dcc.ufmg.br/~msalvim/courses/infotheory/problemset01_DiscreteProbability for the Information Theory course at UFMG.
#+END_abstract

1. (a) The conditions are:
	 - All probabilities should be between 0 and 1 including the sum of all the probabilities on the system.
	 - The sum of all probabilities should be equal to 1. 
	 (b) p(Head or Tails) = 1, p(Head) = 3*p(Tails), then 3*p(Tails) + p(Tails) = 1 \rightarrow p(Tails) = \frac{1}/{4} \rightarrow p(Head) = \frac{3}/{4}.

2. (a) Given the sample space, the conditional probabilities between an event E given that another event F occurred, can be seen as the proportion between all occurrences of E and F occurring together and all the possible ocurrences of F, so P(E | F) = \frac{p(E \cap F)}{p(F)} 
	 (b) Assuming a die of 6 sides, we have {2, 4, 6} as the possible even numbers, F is the event that the die comes with one of the numbers {1, 2, 3}, then ${2, 4, 6} \cap {1, 2, 3} = {2}$, so we have p(F | E) = \frac{|{2}|}{|{2, 4, 6}|} = \frac{1}{3}

3. (a) When the intersection of all the occurences of both is the empty set, what that means is that the occurrence of one event does not impact on the occurrence of the other. In that sense the probability of both occurring is p(A)p(B).
	 (b) Yes, because sinse the die is fair, all numbers have the same probability.

4. (a) A random variable is a projection between a possible outcome of an Event to the real numbers.
	 (b) It will be the numbers {1, 2, 3, 4, 5, 6}.


5. (a) The expected value it weighted average of all the possible outcomes of and random event by their probabilities, it represent the closest value the the value that is more likely to occurr.
	 (b) The number 1 have probability 1/36 of occurring, the number 2 have probability 3/36, the number 3 have probability 5/36, the number 4 have probability 7/36, the number 5 have probability 9/36 and the number 6 have probability 11/36 so the expected value is:

	 1\frac{1}{36} + 2\frac{3}{36} + 3\frac{5}{36} + 4\frac{7}{36} + 5\frac{9}{36} + 6\frac{11}{36} = \frac{1159}{234} \approx 4.952


6. (a) A random experiment with only two possible outcome.
	 (b) C(n, k)p^{k}(1-p)^{n - k} where C(n, k) = \frac{n!}{k!(n-k)1}
	 (c) p \times n

7. (a) That the "how close" the expected value is from an actual experiment value is linearly proportional to its probability.

8. p(F | E) = \frac{p(F)p(E | F)}{p(F)p(E | F) + p(\bar{F})p(E | \bar{F})} \rightarrow p(F | E) = \frac{\frac{2}{3}\frac{1}{3}}{\frac{2}{3}\frac{1}{3} + \frac{1}{3}\frac{1}{4}} = \frac{8}{11}

9. The variance of a random variable is a measurment of how far the real values are from the expected value.

10. p(E \cup F) = p(E) + p(F) - p(E \cap F), we also have that p(E \cup F) <= 1, using the fact that p(E) = 0.7 and p(F) = 0.5, p(E \cup F) = 0.7 + 0.5 - p(E \cap F) <= 1 \right arrow 1.2 - p(E \cap F) <= 1 \rightarrow p(E \cap F) >= 0.2. Sinse p(F) = 0.5, p(E \cup F) >= 0.5, and p(E) = 0.7 we have that p(E \cup F) >= 0.7, by taking the upperbound we have p(E \cup F) >= 0.7. 


11. p(E | F) = p(E) and p(F | E) = p(F), p(F) = p(F \cap E) + p(F \cap \bar{E}), using the independence of E and F we conclude that p(F) = p(F)p(E) + p(F \cap \bar{E}) \rightarrow p(F \cap \bar{E}) = p(F) - p(F)p(E) = p(F)(1 - P(E)) = p(F)p(\bar{E}), and so, F and \bar{E} are independent.
 

12. Listing all strings of length four, we have $B_4 = { 1111, 1110, 1100, 1000, 1011, 1101, 1001, 1010, 0111, 0110, 0100, 0000, 0011, 0101, 0001, 0010 }$ where $|B_4| = 2^4 = 16$, taking all strings of length 4 with two consecutive zeros we have $Z_4 = { 1100,1000,1001,0100,0000,0011,0001,0010 }$ where $|Z_4| = 8$, we can see that among those strings, the set of all strings that start with 1 is $Z1_4 = { 1100, 1000, 1001 }, from that we can see that the probabilty of a string that start with 1 having two consecutive 0's is 3/8, that is the number of strings starting with 1 with at least one sequence of two consecutive 0's divided by the count of strings of size 4 with at least one sequence of two of 0's. 

13. let H be male and M be female, we have a total of 16 configurations for four children that can be H or M, from that we have E = { HHHM, HHMH, HMHH, MHHH, HHMM, HMHM, MHHM, HMMH, MHMH, MMHH, HMMM, MHMM, MMHM, MMMH } and F = { HMMM, MHMM, MMHM, MMMH, MMMM }, that implies that p(E) = \frac{14}{16}, for the events to be independent we need that p(E | F) = p(E), but p(E | F) = \frac{p(E \cap F)}{p(F)} = \frac{\frac{4}{16}}{\frac{5}{16}} = \frac{4}{5} \neq \frac{14}{16}, and so the two events are not independent.

14. let t being the random variable of a patient testing positive and \bar{T} the variable for a patient testing negative, let H being a patient HIV infecter and \bar{H} being a patient not infected with HIV.
		
		p(H) = 0.8

		p(\bar{H}) = 0.92

		p(T | H) = 0.98

		p(T | \bar{H}) = 0.3
		
		(a) p(H | T) = \frac{0.8 \times 0.98}{0.8 \times 0.98 + 0.92 \times 0.3} \approx 0.739. So the patient is infected with probability of 0.73%.
		(b) p(\bar{H} | T) = \frac{0.92 \times 0.3}{0.92 \times 0.3 + 0.8 \times 0.98} \approx 0.26. So the patient is not infected with probability of 0.26%.
		(c) p(H | \bar{T}) = \frac{p(H)p(\bar{T} | H)}{p(H)p(\bar{T}) + p(\bar(H)p(\bar{T} | \bar{H}))} = \frac{0.8 \times 0.2}{0.8 \times 0.2 + 0.92 \times 0.97} \approx 0.15. So the patient is infected with probability of 15%.
		(d) p(\bar{H} | \bar{T}) = \frac{p(\bar{H})p(\bar{T} | \bar{H})}{p(\bar{H})p(\bar{T} | \bar{H}) + p(H)p(\bar{T} | H)} = \frac{0.92 \times 0.97}{0.92 \times 0.97 + 0.8 \times 0.2} \approx 0.84. So the patient is not infected with probability of 84%.
		 
		 
